sudo: false

language: scala
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

jdk:
- openjdk8

script:
  - PLAY_VERSION=2.5 sbt -J-XX:ReservedCodeCacheSize=256M +test
  - PLAY_VERSION=2.6 sbt -J-XX:ReservedCodeCacheSize=256M +test

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

notifications:
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/1d8408a056d3e10bf156'
    on_success: change
    on_failure: always
    on_start: false
